<!--=== Banner ===-->
<div class="breadcrumbs">
    <h2 class="pull-right text-info pbbanner"><strong>Philosophy</strong></h2>
</div>
<!--/Banner-->


<!--=== Content Part ===-->
<div class="container content lead">
<div class="row-fluid row">


<script type="text/javascript">
    window.onload = function(){
var liLabel = 'PHILOSOPHY';
changeSelected(liLabel);
//Side Menu
<?php include("shared-side-nav-aboutus.php"); ?>

	
	<div class=" privacy col-md-9">
	

    <div class="row-fluid privacy">
        
        <p><strong class="text-info"><em>The End of Christian Education</em></strong></p>
        <p>
            As Pope Pius XI wrote in 1939 in his encyclical Divini Illius Magistri (On Christian Education), "The proper and immediate 
            end of Christian education is to cooperate with divine grace in forming the  true  and  perfect Christian, that is, to form 
            Christ Himself in those regenerated by Baptism." A sound Catholic  education is rooted in Christ and grounded in the Church 
            and acknowledges God's presence in all creation. With this knowledge comes humility and a joy for learning.
        </p><br>
        <p><strong class="text-info"><em>Classical Curriculum</em></strong></p>
        <p><strong><em>Classical</em></strong></p>
        <p>
            The classical pedagogy, successfully used by the Church through the ages, is uniquely situated to convey the "permanent 
            things" to young minds eager for truth. This approach is suited to basic human nature and development and has been tested 
            over centuries. Its purpose is  not  to  teach  the  student  everything,  but instead to form in the student the ability 
            to learn new material.  Instead  of teaching what to think, students are taught how to think. It is a rigorous education and 
            equires self-discipline, but it trains students to be analytical and to be able to draw conclusion s. It also fosters curiosity 
            and a love of learning.
        </p>
        <br><p><strong><em>Trivium</em></strong></p>
        <p>
            Mirroring the natural and organic development of the human mind, the classical approach, also known as the Trivium, divides 
            the stages of learning into three: grammatical, dialectical or logical, and rhetorical. The grammatical stage (grades K to 6) 
            emphasizes memorization and the learning of fundamental rules through drills and repetition. As grammar is the foundation for 
            learning language, this stage provides building blocks for later learning. The logical stage (grades 7 to 9) takes these skills 
            acquired in the grammatical stage and employs them for use in logical constructions . The child learns cause and effect, how 
            things relate to each other and how they fit together. A child is ready for this stage when he has the capacity for abstract 
            thought. The rhetorical stage (grades 10 to 12) takes facts and logic from the previous stages and uses them finally for creative 
            purposes. This is when a student learns how to express what he has learned in a coherent fashion and learns the art of persuasive 
            argument.
        </p>
        <br><p><strong><em>Curriculum</em></strong></p>
        <p>
            The classical educational approach is language-based, instead of image-based. The study of Latin and Greek support the study 
            of language. Latin is the language of the Church, the root language of English and the language used by minds educated in the 
            classics throughout the history of Western Civilization. It serves to train the mind in a clear and logical manner.
        </p>
        <p>
            A classical curriculum is history-intensive - many subjects are studied within the context of history, which is divided into 
            four periods (the ancients, the medieval period through the early Renaissance, the late Renaissance through the early modern 
            era, and modern times).
        </p>
        <br><p><strong class="text-info"><em>Parents as the Primary Educators of Children</em></strong></p>
        <p>
            As Pope John Paul II wrote in 1981 in his encyclical Familiaris Consortio (On the Christian Family), "The right and duty of 
            parents to give education is essential, since it is connected with the transmission of human life; it is original and primary 
            with regard to the educational role of others on account of the uniqueness of the loving relationship between parents and 
            children; and  it is irreplaceable and inalienable and therefore incapable of being entirely delegated to others or usurped by 
            others." Just as parents cooperate with God in creation (procreators), so do they cooperate with God's will in their children's 
            salvation. Any formal educational institution can never replace parents in their role, but instead becomes an extension of the 
            family. Teachers and administrators act as stewards toward the parents whose children are in their care, and work in harmony with 
            parents to educate their children.
        </p>

</div></div>

    </div><!--/row-fluid-->
</div><!--/container-->
<!--=== End Content Part ===-->